version: '3.8'

services:
  flask:
    container_name: flask
    build: 
      context: './flask'
      dockerfile: .dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./flask:/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
